USE [Dynasty_DW]
GO

/****** Object:  Table [dbo].[Company_Dim]    Script Date: 7/12/2019 1:43:19 PM ******/

/****** Object:  Table [dbo].[Company_Dim]    Script Date: 7/12/2019 1:43:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[Company_Dim]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		PRINT 'Creating table Company_Dim...'
		CREATE TABLE [dbo].[Company_Dim](
			[Idnmb] [int] IDENTITY(1,1) NOT NULL,
			[CompanyCode] [varchar](50) NULL,
			[CompanyName] [varchar](200) NOT NULL,
			[BillingName] [varchar](200) NULL,
			[GLFlg] [BIT] NULL,
			[CreateDate] [datetime] NOT NULL  CONSTRAINT DF_COMPANY_DIM_CREATEDATE DEFAULT (getdate()),
			[DataLockDate] [datetime] NULL,
		 CONSTRAINT [PK_Company_Dim] PRIMARY KEY CLUSTERED 
		(
			[Idnmb] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
		UNIQUE NONCLUSTERED 
		(
			[CompanyName] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		) ON [PRIMARY]

	END
ELSE
	BEGIN
		print 'Updating the structure of the Company_Dim table...'
	
		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'BillingName')
		Begin
				Alter table Company_Dim add BillingName Varchar(200) null
				Print 'Added BillingName Column'
		End

		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'GLFlg')
		Begin
				Alter table Company_Dim add GLFlg [BIT] null
				Print 'Added GLFlg Column'
		End

		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'Division')
		Begin
				ALTER TABLE COMPANY_DIM ADD DIVISION VARCHAR(50) NULL
				PRINT 'ADDED DIVISION COLUMN'
		End

		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'Division')
		Begin
				ALTER TABLE COMPANY_DIM ADD DIVISION VARCHAR(50) NULL
				PRINT 'ADDED DIVISION COLUMN'
		End

		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'City')
		Begin
				ALTER TABLE COMPANY_DIM ADD City VARCHAR(100) NULL
				PRINT 'ADDED City COLUMN'
		End

		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'State')
		Begin
				ALTER TABLE COMPANY_DIM ADD [State] VARCHAR(100) NULL
				PRINT 'ADDED State COLUMN'
		End

		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'Status')
		Begin
				ALTER TABLE COMPANY_DIM ADD [Status] VARCHAR(100) NULL
				PRINT 'ADDED Status COLUMN'
		End

		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'PreviousFirm')
		Begin
				ALTER TABLE COMPANY_DIM ADD [PreviousFirm] VARCHAR(200) NULL
				PRINT 'ADDED PreviousFirm COLUMN'
		End


		IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Company_Dim' AND COLUMN_NAME = 'RM')
		Begin
				ALTER TABLE COMPANY_DIM ADD [RM] VARCHAR(200) NULL
				PRINT 'ADDED RM COLUMN'
		End

	END
GO

SET ANSI_PADDING OFF
GO


